### PR TITLE
Refactor SUNMOCSV for input of velocity functions via q-files.

### PR DESCRIPTION
**Pull request by l2r-git**
Also refactor to use routines from lib to input velocities (getviacommand and getviaqfile).
And added more tests and examples into demos.

### CODE REVIEW

**Comment by l2r-git** [comment]
I seem to have added the same file to SeisUnix/include and SeisUnix/src/su/include 
I changed some other header files as well.
Those directories seem to require copies of the same header files? 
Anyway I hope you can perform the needed adjustments.

**Comment by l2r-git** [comment]
I seem to have added the same file to SeisUnix/include and SeisUnix/src/su/include 
I changed some other header files as well.
Those directories seem to require copies of the same header files? 
Anyway I hope you can perform the needed adjustments.

**Comment by JohnWStockwellJr** [comment]
Refactor SUNMOCSV for input of velocity functions via q-files.

**Comment by JohnWStockwellJr** [comment]
Thank you for the updates



John Stockwell   | ***@***.***

https://wiki.Seismic-Unix.org 
(The New Home of Seismic Un*x)

**Pull request merged**
