### PR TITLE
Do not check in java class files.

### PR DESCRIPTION
**Pull request by schwehr**
```find . -name \*.class | xargs git rm```

Where are the original java files?

### CODE REVIEW

**Comment by schwehr** [comment]
@JohnWStockwellJr It would be nice if you can explain why you closed this without mergring.  Thx.

**Comment by JohnWStockwellJr** [comment]
There are no Java codes in SU

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by schwehr** [comment]
If it's important enough to SU, how about at least adding a readme to where the source is rather than forcing anyone needing to make a change to decompile the java?

**Comment by JohnWStockwellJr** [comment]
There is no Java in SU

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by schwehr** [comment]
But there are...  added in https://github.com/JohnWStockwellJr/SeisUnix/commit/e09d3d69f0ab0d5363640ea35d60935e7b6c4918 on 2016-Apr-04

Here are just a few of the compiled java files:

```
find . -name a\*.class | xargs file
./src/Gui/dsulinux.old/dsu/gui/argsDialog$1.class: compiled Java class data, version 45.3
./src/Gui/dsulinux.old/dsu/gui/applDialog.class:   compiled Java class data, version 45.3
./src/Gui/dsulinux.old/dsu/gui/argsDialog.class:   compiled Java class data, version 45.3
./src/Gui/sugui/classes/argsDialog$1.class:        compiled Java class data, version 45.3
./src/Gui/sugui/classes/applDialog.class:          compiled Java class data, version 45.3
./src/Gui/sugui/classes/argsDialog.class:          compiled Java class data, version 45.3
```

Based on [Java class file versions](https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers), this looks to be built with JDK 1.1... from the 90s ([Java version history](https://en.wikipedia.org/wiki/Java_version_history)).  If this stuff still works, it could probably greatly benefit from being recompiled with a newer version of java.

Looking at the README, it's not obvious where to find the original java sources.

But it's clearly java:

```
procyon DSUCONTROLLER.class > DSUCONTROLLER.java
```

Gives

```java

class DSUCONTROLLER extends Panel implements ActionListener
{
    public DSUGRAPH currentGraph;
    public DSUCANVAS DsuGraphCanvas;
    public DSUTABLEOFAPPL table;
    public DSUCONTROLPANEL controlPanel;
    public DSULISTOFGRAPHS graphList;
    public Panel DsuGraphView;
    public MenuBar menubar;
    public TextArea infoarea;
    public FileDialog file_dialog;
    private Frame mainFrame;
    int msgcounter;
    String confirmedFn;
    
    public DSUCONTROLLER(final Frame frame) {
        this.mainFrame = frame;
        this.table = new DSUTABLEOFAPPL(frame, this, String.valueOf(System.getProperties().getProperty("DSUGUIDIR")) + "/categories");
        this.currentGraph = new DSUGRAPH(this, "default");
        (this.graphList = new DSULISTOFGRAPHS(frame, 10)).add(this.currentGraph);
        this.DsuGraphCanvas = new DSUCANVAS(this, Color.red);
        final ScrollPane comp = new ScrollPane(1);
        comp.add(this.DsuGraphCanvas);
        (this.DsuGraphView = new Panel()).setLayout(new BorderLayout());
        this.DsuGraphView.add("North", new Label("Graph of the sequence", 1));
        this.DsuGraphView.add("Center", comp);
        this.controlPanel = new DSUCONTROLPANEL(this);
        this.menubar = this.controlPanel.menubar;
        this.infoarea = this.controlPanel.infoarea;
        this.file_dialog = new FileDialog(frame, "Open File", 0);
    }
    
    public void dumpmsg(final String str) {
        ++this.msgcounter;
        this.infoarea.append(String.valueOf(this.msgcounter) + ": " + str);
    }
    
    public void addmsg(final String str) {
        this.infoarea.append(str);
    }
    
    public void quit() {
        final YesNoDialog yesNoDialog = new YesNoDialog(this.mainFrame, "Really Quit?", "Are you sure you want to quit?", "Yes", "No", null);
        yesNoDialog.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent actionEvent) {
                if (actionEvent.getActionCommand().equals("yes")) {
                    System.exit(0);
                    return;
                }
                DSUCONTROLLER.this.dumpmsg("Quit not confirmed\n");
            }
        });
        yesNoDialog.show();
    }

// [SNIP]
```

**Comment by JohnWStockwellJr** [comment]
Thanks. I will remove it. One of the many abortive attempts to write a GUI for SU. 

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Pull request closed without merging**
